services:
  - type: web
    name: friendly-greetings-launchpad
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    # Force Docker build and disable pip install
    buildCommand: docker build --no-cache -t friendly-greetings-launchpad .
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://friendly-greetings-launchpad-1-o4pr.onrender.com,http://localhost:5173,http://localhost:8080
      - key: PYTHON_VERSION
        value: "3.9.18"
      - key: PIP_NO_BUILD_ISOLATION
        value: "false"
