services:
  - type: web
    name: friendly-greetings-launchpad
    env: docker
    plan: free
    buildCommand: |
      # Frontend and backend will be built by Dockerfile
      # No additional build steps needed
      echo "Build handled by Dockerfile"
    startCommand: python fastapi_backend.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: NODE_VERSION
        value: 18.x
    healthCheckPath: /
    autoDeploy: true
