services:
  - type: web
    name: friendly-greetings-launchpad
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    autoDeploy: true
    envVars:
      - key: CORS_ALLOWED_ORIGINS
        value: https://friendly-greetings-launchpad-1-v831.onrender.com,http://localhost:5173,http://localhost:8080
